export { default as LoginContainer} from './auth/Login'
export { default as SignupContainer} from './auth/Signup'
export { default as ForgotContainer} from './auth/ForgotPassword'
export { default as EnterOtp} from './auth/EnterOtp'
export { default as ForgotOtp} from './auth/ForgotOtp'
export { default as ResetPassword} from './auth/ResetPassword' 
export { default as Home} from './Home' 
export {default as ProductList} from './product/productListing'
export {default as ProductDetail} from './product/ProductDetail'
export {default as Profile} from './auth/Profile'
export {default as Products} from './product/Products'