export const effectedPerson = "Please select a person";
export const effectedSite = "Please select site";
export const effectedIncident = "Please select incident";
export const effectedMachiene = "Please selet a machine";
export const emptyEmail="Please enter your email address.";
export const invalidEmail="Please enter a valid email address.";
export const emptyPassword = "Please enter your password";
export const emptyCPassword = "Please enter your confirm password";
export const firstName = "Please enter your firstname";
export const lastName = "Please enter your lastname";
export const emptyMobile = "Please enter your mobile number";
export const invalidPhone ="Please enter a valid mobile number.";
export const invalidName = "Please enter your name"
export const invalidOtp = "please enter OTP"
