export const LOGIN_REQUEST = 'ILOGIN_REQUEST' 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST' 
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const VERIFICATION_REQUEST = 'VERIFICATION_REQUEST' 
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS'
export const VERIFICATION_FAIL = 'VERIFICATION_FAIL'

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST' 
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'

export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST' 
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL'

export const MY_LISTING_REQUEST = 'MY_LISTING_REQUEST' 
export const MY_LISTING_SUCCESS = 'MY_LISTING_SUCCESS'
export const MY_LISTING_FAIL = 'MY_LISTING_FAIL'

export const CATEGORY_DATA_REQUEST = 'CATEGORY_DATA_REQUEST' 
export const  CATEGORY_DATA_SUCCESS = 'CATEGORY_DATA_SUCCESS'
export const CATEGORY_DATA_FAIL = 'CATEGORY_DATA_FAIL'

export const PRODUCT_DATA_REQUEST = 'PRODUCT_DATA_REQUEST' 
export const  PRODUCT_DATA_SUCCESS = 'PRODUCT_DATA_SUCCESS'
export const PRODUCT_DATA_FAIL = 'PRODUCT_DATA_FAIL'